# Generated by Django 4.2.22 on 2025-06-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorProfile',
            fields=[
                ('investor_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('industry', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('address', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'investor',
                'verbose_name_plural': 'investors',
                'db_table': 'investors',
            },
        ),
    ]
