# Generated by Django 4.2.21 on 2025-05-20 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Startup",
            fields=[
                ("startup_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("industry", models.CharField(blank=True, max_length=255, null=True)),
                ("website", models.CharField(blank=True, max_length=255, null=True)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "user_id",
                    models.OneToOneField(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "startup",
                "verbose_name_plural": "startups",
                "db_table": "startups",
            },
        ),
        migrations.CreateModel(
            name="Investor",
            fields=[
                ("investor_id", models.AutoField(primary_key=True, serialize=False)),
                ("company_name", models.CharField(max_length=255)),
                ("industry", models.CharField(blank=True, max_length=255, null=True)),
                ("required_funding", models.IntegerField()),
                ("created_at", models.DateField(auto_now_add=True)),
                ("address", models.CharField(max_length=255)),
                ("website", models.CharField(max_length=255)),
                (
                    "user_id",
                    models.OneToOneField(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "investor",
                "verbose_name_plural": "investors",
                "db_table": "investors",
            },
        ),
    ]
